server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1050795534619-nue99ve1dd5knotv3f3lmqurqh3714lu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1352822688524641
            client-secret: 620e1b97bcc211aeffc974672ec30213
            scope:
              - email
              - public_profile

          naver:
            clientId: 9wbC7imRslY7gDPTBV7L
            clientSecret: n__GyqrDqR
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response # 회원 정보를 json 으로 받는데 response 라는 키-값으로 네이버가 리턴해준다.